CREATE TABLE `ZONETYPE` (
  `ZONETYPEID` int(32) NOT NULL auto_increment PRIMARY KEY UNIQUE KEY,
  `NAME` varchar(32) NOT NULL default '',
  `DESCRIPTION` TEXT NOT NULL default ''
) TYPE=InnoDB;

INSERT INTO ZONETYPE VALUES (1,'Primary','Static Primary Zone');
INSERT INTO ZONETYPE VALUES (2,'Secondary','Secondary Zone');
INSERT INTO ZONETYPE VALUES (3,'Dynamic','Dynamic Primary Zone');

CREATE TABLE `ZONESTATUS` (
`ZONESTATUSID` int(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
`NAME` varchar(32) NOT NULL default '',
`DESCRIPTION` TEXT NOT NULL default ''
) TYPE=INNODB;

INSERT INTO ZONESTATUS VALUES (1,'Enabled','Zone Active');
INSERT INTO ZONESTATUS VALUES (2,'Disabled','Zone InActive');

CREATE TABLE `ZONES` (
  `ZONEID` int(32) NOT NULL auto_increment PRIMARY KEY UNIQUE KEY,
  `ZONETYPEID` int(32) NOT NULL default '0',
  `ZONESTATUSID` INT(32) NOT NULL,
  `NAME` varchar(128) NOT NULL default '' UNIQUE,
  `UPDATED` tinyint(1) NOT NULL DEFAULT '0',
  KEY `ZONETYPEID` (`ZONETYPEID`),
  KEY `ZONESTATUSID` (`ZONESTATUSID`),
  FOREIGN KEY (`ZONETYPEID`) REFERENCES `ZONETYPE` (`ZONETYPEID`),
  FOREIGN KEY (`ZONESTATUSID`) REFERENCES `ZONESTATUS` (`ZONESTATUSID`)
) TYPE=InnoDB;

 CREATE TABLE `USERACCOUNTTYPE` ( 
 `USERACCOUNTTYPEID` INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY, 
 `NAME` VARCHAR(32) NOT NULL, 
 `DESCRIPTION` TEXT NOT NULL 
) TYPE = InnoDB;

INSERT INTO USERACCOUNTTYPE VALUES (1,'Admin','Administrator Account');
INSERT INTO USERACCOUNTTYPE VALUES (2,'User','User Account');
INSERT INTO USERACCOUNTTYPE VALUES (3,'Read-Only-Admin','Read Only Administrator');
INSERT INTO USERACCOUNTTYPE VALUES (4,'Read-Only-User','Read Only User');

CREATE TABLE `USERACCOUNT` (
  `USERID` int(32) NOT NULL auto_increment PRIMARY KEY UNIQUE KEY,
  `USERNAME` varchar(64) NOT NULL default '' UNIQUE,
  `PASSWORD` varchar(128) NOT NULL default '',
  `USERACCOUNTTYPEID` int(32) NOT NULL default '0',
  `FULLNAME` varchar(128) NULL,
  KEY `USERTYPEID` (`USERACCOUNTTYPEID`),
  FOREIGN KEY (`USERACCOUNTTYPEID`) REFERENCES `USERACCOUNTTYPE` (`USERACCOUNTTYPEID`)
) TYPE=InnoDB;

CREATE TABLE `PRIMARYUSERREF` ( 
`PRIMARYREFID` INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY, 
`ZONEID` INT(32) NOT NULL, 
`USERID` INT(32) NOT NULL,
KEY `ZONEID` (`ZONEID`),
KEY `USERID` (`USERID`),
FOREIGN KEY (`ZONEID`) REFERENCES `ZONES`(`ZONEID`),
FOREIGN KEY (`USERID`) REFERENCES `USERACCOUNT`(`USERID`)
) TYPE = InnoDB;

CREATE TABLE `SECONDARYUSERREF` ( 
`SECONDARYREFID` INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY, 
`ZONEID` INT(32) NOT NULL, 
`USERID` INT(32) NOT NULL,
KEY `ZONEID` (`ZONEID`),
KEY `USERID` (`USERID`),
FOREIGN KEY (`ZONEID`) REFERENCES `ZONES`(`ZONEID`),
FOREIGN KEY (`USERID`) REFERENCES `USERACCOUNT`(`USERID`)
) TYPE = InnoDB;

CREATE TABLE `RECORDTYPE` (
`RECORDTYPEID` INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
`NAME` varchar(32) NOT NULL default '',
`DESCRIPTION` TEXT NOT NULL default '',
`SORTORDER` INT(32) NOT NULL
) TYPE = InnoDB;

INSERT INTO RECORDTYPE VALUES (1,'A','Address Record',4);
INSERT INTO RECORDTYPE VALUES (2,'A6','IPV6 Address Record',5);
INSERT INTO RECORDTYPE VALUES (3,'CNAME','Canonical name',6);
INSERT INTO RECORDTYPE VALUES (4,'HINFO','Host Info',7);
INSERT INTO RECORDTYPE VALUES (5,'MX','Mail Exchanger',3);
INSERT INTO RECORDTYPE VALUES (6,'NS','Name Server',1);
INSERT INTO RECORDTYPE VALUES (7,'PTR','Pointer Record',9);
INSERT INTO RECORDTYPE VALUES (8,'SOA','Start of Authority',0);
INSERT INTO RECORDTYPE VALUES (9,'TXT','Text Record',8);


CREATE TABLE `RECORDS` (
`RECORDID` INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
`ZONEID` INT(32) NOT NULL,
`MODUSER` VARCHAR(32) NOT NULL,
`RECORDTYPEID` INT(32) NOT NULL,
`RECORD` VARCHAR(64) NOT NULL default '',
`TTL` INT(32),
`MXPRIORITY` INT(32),
`VALUE` VARCHAR(255) NOT NULL default '', 
KEY `ZONEID` (`ZONEID`),
KEY `RECORDTYPEID` (`RECORDTYPEID`),
FOREIGN KEY (`ZONEID`) REFERENCES `ZONES`(`ZONEID`),
FOREIGN KEY (`RECORDTYPEID`) REFERENCES `RECORDTYPE`(`RECORDTYPEID`)
) TYPE=INNODB;

CREATE TABLE LOGENTRYTYPE (
`LOGENTRYTYPEID` INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
`NAME` VARCHAR(32) NOT NULL default '',
`DESCRIPTION` TEXT NOT NULL default ''
) TYPE=INNODB;

INSERT INTO LOGENTRYTYPE VALUES (1,'SUCCESS','Login Success');
INSERT INTO LOGENTRYTYPE VALUES (2,'FAILURE','Login Failure');
INSERT INTO LOGENTRYTYPE VALUES (3,'ADDRECORD','Add a Record');
INSERT INTO LOGENTRYTYPE VALUES (4,'DELRECORD','Delete a Record');
INSERT INTO LOGENTRYTYPE VALUES (5,'ADDDOMAIN','Add a Domain');
INSERT INTO LOGENTRYTYPE VALUES (6,'DELDOMAIN','Delete a Domain');
INSERT INTO LOGENTRYTYPE VALUES (7,'ADDUSER','Add a User');
INSERT INTO LOGENTRYTYPE VALUES (8,'DELUSER','Delete a User');
INSERT INTO LOGENTRYTYPE VALUES (9,'TIMEOUT','User Session Timed Out');
INSERT INTO LOGENTRYTYPE VALUES (10,'CONFIG','Config Value Changed');
INSERT INTO LOGENTRYTYPE VALUES (11,'BYPASS','Security Bypass');
INSERT INTO LOGENTRYTYPE VALUES (12,'NOPRIVILEDGES','No Priviledges for Function');
INSERT INTO LOGENTRYTYPE VALUES (13,'MODRECORD','Modified Zone Record');
INSERT INTO LOGENTRYTYPE VALUES (14,'MODUSER','Modify a User Account');
INSERT INTO LOGENTRYTYPE VALUES (15,'CHANGESTATUS','Change Zone Status');
INSERT INTO LOGENTRYTYPE VALUES (16,'UPDATESECONDARY','Update Primary IP');
INSERT INTO LOGENTRYTYPE VALUES (17,'LOGOUT','Logout of User');
INSERT INTO LOGENTRYTYPE VALUES (18,'MODZONEOPTION','Modification of Zone Options');

CREATE TABLE LOG (
  LOGID INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
  USERNAME TEXT NOT NULL,
  TIME TIME NOT NULL default '00:00:00',
  DATE DATE NOT NULL default '0000-00-00',
  IP TEXT NOT NULL,
  LOGENTRYTYPEID INT(32) NOT NULL,
  RELATEDINFO TEXT NULL,
  KEY `LOGENTRYTYPEID` (`LOGENTRYTYPEID`),
  FOREIGN KEY (`LOGENTRYTYPEID`) REFERENCES `LOGENTRYTYPE`(`LOGENTRYTYPEID`) 
) TYPE=INNODB;

CREATE TABLE ZONEOPTIONTYPE (
ZONEOPTIONTYPEID INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
NAME VARCHAR(32) NOT NULL,
DESCRIPTION TEXT NOT NULL
) TYPE=INNODB;

INSERT INTO ZONEOPTIONTYPE VALUES (1,'DYNAMICUPDATEIP','List of IP\'s allowed to Perform Dynamic Updates');
INSERT INTO ZONEOPTIONTYPE VALUES (2,'ALSONOTIFY','List of IP\'s to Notify allong with NS records');
INSERT INTO ZONEOPTIONTYPE VALUES (3,'OUTPUTDIR','Output Directory for zone files relative to ZONEDIRABS (must exist)');

CREATE TABLE ZONEOPTIONS (
ZONEOPTIONID INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
ZONEID INT(32) NOT NULL,
ZONEOPTIONTYPEID INT(32) NOT NULL,
VALUE VARCHAR(128)  NOT NULL,
KEY `ZONEID` (`ZONEID`),
KEY `ZONEOPTIONTYPEID` (`ZONEOPTIONTYPEID`),
FOREIGN KEY (`ZONEID`) REFERENCES `ZONES`(`ZONEID`),
FOREIGN KEY (`ZONEOPTIONTYPEID`) REFERENCES `ZONEOPTIONTYPE`(`ZONEOPTIONTYPEID`)
) TYPE=INNODB;

CREATE TABLE PROGRAMOPTIONTYPE (
PROGRAMOPTIONTYPEID INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
NAME VARCHAR(32) NOT NULL,
DESCRIPTION TEXT NOT NULL
) TYPE=INNODB;

INSERT INTO PROGRAMOPTIONTYPE VALUES (1,'ADMINEMAIL','Administrator Email');
INSERT INTO PROGRAMOPTIONTYPE VALUES (2,'KEY','Seed For Password Encryption');
INSERT INTO PROGRAMOPTIONTYPE VALUES (3,'DNSADMIN','Server Admin for SOA records');
INSERT INTO PROGRAMOPTIONTYPE VALUES (4,'ORIGINSERVER','Origin DNS Server for SOA records');
INSERT INTO PROGRAMOPTIONTYPE VALUES (5,'CONFIGHEADER','Header of named.conf');
INSERT INTO PROGRAMOPTIONTYPE VALUES (6,'CONFDIRABS','Absolute path to named.conf');
INSERT INTO PROGRAMOPTIONTYPE VALUES (7,'ZONEDIRABS','Absolute path to zone files');
INSERT INTO PROGRAMOPTIONTYPE VALUES (8,'ZONEDIR','Relative path to zone files');
INSERT INTO PROGRAMOPTIONTYPE VALUES (9,'RNDCPATH','Path to rndc executable with commandline parameters');
INSERT INTO PROGRAMOPTIONTYPE VALUES (10,'DIGPATH','Path to dig executable');
INSERT INTO PROGRAMOPTIONTYPE VALUES (11,'SERIALSTRING','Date Format string for php date function used to create serial numbers\nIf you dont know what to enter here enter Ymd01');
INSERT INTO PROGRAMOPTIONTYPE VALUES (12,'REFRESH','Default refresh value for new zones (seconds)');
INSERT INTO PROGRAMOPTIONTYPE VALUES (13,'RETRY','Default retry value for new zones (seconds)');
INSERT INTO PROGRAMOPTIONTYPE VALUES (14,'EXPIRE','Default expire value for new zones (seconds)');
INSERT INTO PROGRAMOPTIONTYPE VALUES (15,'MINIMUM','Default minimum value for new zones (seconds)');
INSERT INTO PROGRAMOPTIONTYPE VALUES (16,'LISTINGMODE','Listing Mode to use (search or listing)');
INSERT INTO PROGRAMOPTIONTYPE VALUES (17,'OUTPUT_FORMAT','Output format (bind/djbdns)');
INSERT INTO PROGRAMOPTIONTYPE VALUES (18,'TIMEOUT','Login Timeout (seconds)');
INSERT INTO PROGRAMOPTIONTYPE VALUES (19,'STYLESHEET','Style Sheet for the app');
INSERT INTO PROGRAMOPTIONTYPE VALUES (20,'AUTOADDSOA','Automatically Add SOA Records to New Zones');
INSERT INTO PROGRAMOPTIONTYPE VALUES (21,'LISTINGRECORDS','Number Of Records to Show Per Page in Listing Mode');
INSERT INTO PROGRAMOPTIONTYPE VALUES (22,'CONFIRMDELETE','Confirm Delete Actions (yes,no,user)');

CREATE TABLE PROGRAMOPTIONS (
PROGRAMOPTIONID INT(32) NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE KEY,
PROGRAMOPTIONTYPEID INT(32) NOT NULL,
VALUE TEXT NOT NULL,
KEY `PROGRAMOPTIONTYPEID` (`PROGRAMOPTIONTYPEID`),
FOREIGN KEY (`PROGRAMOPTIONTYPEID`) REFERENCES `PROGRAMOPTIONTYPE`(`PROGRAMOPTIONTYPEID`)
) TYPE=INNODB;
ALTER TABLE PROGRAMOPTIONS ADD UNIQUE PROGRAMOPTIONTYPEIDUNI (PROGRAMOPTIONTYPEID);

CREATE TABLE PRIMARYIP (
ZONEID	INT(32) NOT NULL PRIMARY KEY UNIQUE KEY,
IP TEXT NOT NULL,
KEY `PRIIPZONEID` (`ZONEID`),
FOREIGN KEY (`ZONEID`) REFERENCES `ZONES`(`ZONEID`)
) TYPE=INNODB;

